### ISSUE TITLE
Online locations as links

### ISSUE THREAD

**Issue by HOOK-Hawkins** [JM-Lemmi/ical-relay#140]
Please render online locations as links.
Suggestion: Please also don't display the complete URL, but a replacement like 'Link' to contain the url to keep the events from getting gigantic.

**Comment by frereit** [comment]
![image](https://user-images.githubusercontent.com/18506129/231875466-c97f55d3-b4c3-406e-aaf4-23a82c043272.png)

This would be my suggestion for how to show this in the frontend? I'm against just replacing all URLs with `<a href=...>Online</a>` because we do not want to train users to click on links when they don't know where they lead imo.

Always only showing the hostname might be a nice middleground between long links and readable links.
